name: build and test
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11', '17' ]
        architecture: [ 'x64' ]
    name: Build with JDK ${{ matrix.java }} on ${{ matrix.architecture }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          architecture: ${{ matrix.architecture }}
          cache: 'gradle'
      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew check --info --warning-mode all
      - uses: codecov/codecov-action@v3
